sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

before_install:
  - docker pull debian:stable-slim

script:
  - docker version
  - docker build --no-cache --tag lltest/gamesvr-tf2 --tag lacledeslan/gamesvr-tf2 --build-arg BUILDNODE=TravisCI --build-arg SOURCE_COMMIT="$TRAVIS_COMMIT" ./linux
  - docker run -it --rm lltest/gamesvr-tf2 ./ll-tests/gamesvr-tf2.sh
